const portfolioImagesMap = {
  // Space Art
  0: {
    images: [
      "./images/gallery/space-art/4-refresh-by-mario-iliev.jpg",
      "./images/gallery/space-art/2-disturbia-by-mario-iliev.jpg",
      "./images/gallery/space-art/3-ancient-apprehension-by-mario-iliev.jpg",
      "./images/gallery/space-art/1-back-to-life-by-mario-iliev.jpg",
      "./images/gallery/space-art/5-chronicles-of-light-by-mario-iliev.jpg",
      "./images/gallery/space-art/6-future-zonia-by-mario-iliev.jpg",
      "./images/gallery/space-art/7-nebula-alive-0014-by-mario-iliev.jpg",
      "./images/gallery/space-art/8-black-absorb-by-mario-iliev.jpg",
      "./images/gallery/space-art/9-lucky-shots-by-mario-iliev.jpg",
      "./images/gallery/space-art/10-quiet-shine-by-mario-iliev.jpg",
      "./images/gallery/space-art/11-orion-by-mario-iliev.jpg",
    ],
    thumbs: [
      "./images/gallery/space-art/4-refresh-tmb-by-mario-iliev.jpg",
      "./images/gallery/space-art/2-disturbia-tmb-by-mario-iliev.jpg",
      "./images/gallery/space-art/3-ancient-apprehension-tmb-by-mario-iliev.jpg",
      "./images/gallery/space-art/1-back-to-life-tmb-by-mario-iliev.jpg",
      "./images/gallery/space-art/5-chronicles-of-light-tmb-by-mario-iliev.jpg",
      "./images/gallery/space-art/6-future-zonia-tmb-by-mario-iliev.jpg",
      "./images/gallery/space-art/7-nebula-alive-0014-tmb-by-mario-iliev.jpg",
      "./images/gallery/space-art/8-black-absorb-tmb-by-mario-iliev.jpg",
      "./images/gallery/space-art/9-lucky-shots-tmb-by-mario-iliev.jpg",
      "./images/gallery/space-art/10-quiet-shine-tmb-by-mario-iliev.jpg",
      "./images/gallery/space-art/11-orion-tmb-by-mario-iliev.jpg",
    ],
  },
  // Digital Art
  1: {
    images: [
      "./images/gallery/digital/1.Cosmos_Room_by_www-marioiliev-com.jpg",
      "./images/gallery/digital/2.The_Speed_of_Darkness_by_www-marioiliev-com.jpg",
      "./images/gallery/digital/3.Nowhere_by_www-marioiliev-com.jpg",
      "./images/gallery/digital/4.Area_51_by_www-marioiliev-com.jpg",
      "./images/gallery/digital/5.Bass_by_www-marioiliev-com.jpg",
      "./images/gallery/digital/6.The_Protoss_by_www-marioiliev-com.jpg",
      "./images/gallery/digital/7.Gold_Wood_by_www-marioiliev-com.jpg",
      "./images/gallery/digital/8.Alien_by_www-marioiliev-com.jpg",
      "./images/gallery/digital/9.Life_is_Short_by_www-marioiliev-com.jpg",
      "./images/gallery/digital/10.Purgatory_by_www-marioiliev-com.jpg",
      "./images/gallery/digital/11.Simple_Droid_by_www-marioiliev-com.jpg",
      "./images/gallery/digital/12.Spirits_by_www-marioiliev-com.jpg",
      "./images/gallery/digital/13.Walking_With_my_Shadow_by_www-marioiliev-com.jpg",
      "./images/gallery/digital/14.Hiding_Devil_by_www-marioiliev-com.jpg",
    ],
    thumbs: [
      "./images/gallery/digital/1.Cosmos_Room_by_www-marioiliev-com-tmb.jpg",
      "./images/gallery/digital/2.The_Speed_of_Darkness_by_www-marioiliev-com-tmb.jpg",
      "./images/gallery/digital/3.Nowhere_by_www-marioiliev-com-tmb.jpg",
      "./images/gallery/digital/4.Area_51_by_www-marioiliev-com-tmb.jpg",
      "./images/gallery/digital/5.Bass_by_www-marioiliev-com-tmb.jpg",
      "./images/gallery/digital/6.The_Protoss_by_www-marioiliev-com-tmb.jpg",
      "./images/gallery/digital/7.Gold_Wood_by_www-marioiliev-com-tmb.jpg",
      "./images/gallery/digital/8.Alien_by_www-marioiliev-com-tmb.jpg",
      "./images/gallery/digital/9.Life_is_Short_by_www-marioiliev-com-tmb.jpg",
      "./images/gallery/digital/10.Purgatory_by_www-marioiliev-com-tmb.jpg",
      "./images/gallery/digital/11.Simple_Droid_by_www-marioiliev-com-tmb.jpg",
      "./images/gallery/digital/12.Spirits_by_www-marioiliev-com-tmb.jpg",
      "./images/gallery/digital/13.Walking_With_my_Shadow_by_www-marioiliev-com-tmb.jpg",
      "./images/gallery/digital/14.Hiding_Devil_by_www-marioiliev-com-tmb.jpg",
    ],
  },
  // Traditional art
  2: {
    images: [
      "./images/gallery/traditional/1.Mental_make_up_by_www-marioiliev-com.jpg",
      "./images/gallery/traditional/2.3D_Confusion_by_www-marioiliev-com.jpg",
      "./images/gallery/traditional/3.The_Nest_and_the_City_by_www-marioiliev-com.jpg",
      "./images/gallery/traditional/4.Own_the_Town_by_www-marioiliev-com.jpg",
      "./images/gallery/traditional/5.Step_by_Step_by_www-marioiliev-com.jpg",
      "./images/gallery/traditional/6.Passage_Minds_by_www-marioiliev-com.jpg",
      "./images/gallery/traditional/7.Rotten_Device_by_www-marioiliev-com.jpg",
      "./images/gallery/traditional/8.Avidity_desease_by_www-marioiliev-com.jpg",
      "./images/gallery/traditional/9.The_Other_Nature_by_www-marioiliev-com.jpg",
      "./images/gallery/traditional/10.Trapped_by_www-marioiliev-com.jpg",
      "./images/gallery/traditional/11.Brain_Cluster_by_www-marioiliev-com.jpg",
      "./images/gallery/traditional/12.Queen_of_Blades_by_www-marioiliev-com.jpg",
      "./images/gallery/traditional/13.Squid_guy_by_www-marioiliev-com.jpg",
      "./images/gallery/traditional/14.Abstract_Space_by_www-marioiliev-com.jpg",
      "./images/gallery/traditional/15.Nature_Oil_Painting_by_www-marioiliev-com.jpg",
      "./images/gallery/traditional/16.Paradise_Oil_Painting_by_www-marioiliev-com.jpg",
      "./images/gallery/traditional/17.After_Winter_Oil_Painting_by_www-marioiliev-com.jpg",
      "./images/gallery/traditional/18.Pastel_Space_by_www-marioiliev-com.jpg",
    ],
    thumbs: [
      "./images/gallery/traditional/1.Mental_make_up_by_www-marioiliev-com-tmb.jpg",
      "./images/gallery/traditional/2.3D_Confusion_by_www-marioiliev-com-tmb.jpg",
      "./images/gallery/traditional/3.The_Nest_and_the_City_by_www-marioiliev-com-tmb.jpg",
      "./images/gallery/traditional/4.Own_the_Town_by_www-marioiliev-com-tmb.jpg",
      "./images/gallery/traditional/5.Step_by_Step_by_www-marioiliev-com-tmb.jpg",
      "./images/gallery/traditional/6.Passage_Minds_by_www-marioiliev-com-tmb.jpg",
      "./images/gallery/traditional/7.Rotten_Device_by_www-marioiliev-com-tmb.jpg",
      "./images/gallery/traditional/8.Avidity_desease_by_www-marioiliev-com-tmb.jpg",
      "./images/gallery/traditional/9.The_Other_Nature_by_www-marioiliev-com-tmb.jpg",
      "./images/gallery/traditional/10.Trapped_by_www-marioiliev-com-tmb.jpg",
      "./images/gallery/traditional/11.Brain_Cluster_by_www-marioiliev-com-tmb.jpg",
      "./images/gallery/traditional/12.Queen_of_Blades_by_www-marioiliev-com-tmb.jpg",
      "./images/gallery/traditional/13.Squid_guy_by_www-marioiliev-com-tmb.jpg",
      "./images/gallery/traditional/14.Abstract_Space_by_www-marioiliev-com-tmb.jpg",
      "./images/gallery/traditional/15.Nature_Oil_Painting_by_www-marioiliev-com-tmb.jpg",
      "./images/gallery/traditional/16.Paradise_Oil_Painting_by_www-marioiliev-com-tmb.jpg",
      "./images/gallery/traditional/17.After_Winter_Oil_Painting_by_www-marioiliev-com-tmb.jpg",
      "./images/gallery/traditional/18.Pastel_Space_by_www-marioiliev-com-tmb.jpg",
    ],
  },
  // Websites
  3: {
    images: [
      "./images/gallery/web-design/1-Portfolio-Hojaplata-www-marioiliev-com.jpg",
      "./images/gallery/web-design/2-Portfolio-MarioIliev-www-marioiliev-com.jpg",
      "./images/gallery/web-design/3-Portfolio-Bourquinch-www-marioiliev-com.jpg",
      "./images/gallery/web-design/4-Portfolio-DobavkiIZdrave-www-marioiliev-com.jpg",
      "./images/gallery/web-design/5-Portfolio-Peopleofideas-www-marioiliev-com.jpg",
      "./images/gallery/web-design/6-Portfolio-Viktor-Petrov-www-marioiliev-com.jpg",
      "./images/gallery/web-design/7-Portfolio-KREARO-www-marioiliev-com.jpg",
      "./images/gallery/web-design/8-Portfolio-RIDEKITE-www-marioiliev-com.jpg",
      "./images/gallery/web-design/9-Portfolio-STEINS-www-marioiliev-com.jpg",
      "./images/gallery/web-design/10-Portfolio-PROKASRO-www-marioiliev-com.jpg",
      "./images/gallery/web-design/11-Portfolio-ALLPELLET-www-marioiliev-com.jpg",
    ],
    thumbs: [
      "./images/gallery/web-design/1-Portfolio-Hojaplata-www-marioiliev-com-tmb.jpg",
      "./images/gallery/web-design/2-Portfolio-MarioIliev-www-marioiliev-com-tmb.jpg",
      "./images/gallery/web-design/3-Portfolio-Bourquinch-www-marioiliev-com-tmb.jpg",
      "./images/gallery/web-design/4-Portfolio-DobavkiIZdrave-www-marioiliev-com-tmb.jpg",
      "./images/gallery/web-design/5-Portfolio-Peopleofideas-www-marioiliev-com-tmb.jpg",
      "./images/gallery/web-design/6-Portfolio-Viktor-Petrov-www-marioiliev-com-tmb.jpg",
      "./images/gallery/web-design/7-Portfolio-KREARO-www-marioiliev-com-tmb.jpg",
      "./images/gallery/web-design/8-Portfolio-RIDEKITE-www-marioiliev-com-tmb.jpg",
      "./images/gallery/web-design/9-Portfolio-STEINS-www-marioiliev-com-tmb.jpg",
      "./images/gallery/web-design/10-Portfolio-PROKASRO-www-marioiliev-com-tmb.jpg",
      "./images/gallery/web-design/11-Portfolio-ALLPELLET-www-marioiliev-com-tmb.jpg",
    ],
  },
  // Logos
  4: {
    images: [
      "./images/gallery/logos/1-Logo-HojaPlata-www-marioiliev-com.jpg",
      "./images/gallery/logos/2-Logo-osfeo-www-marioiliev-com.jpg",
      "./images/gallery/logos/3-Logo-Bourquin-www-marioiliev-com.jpg",
      "./images/gallery/logos/4-Logo-Shishmanovi-www-marioiliev-com.jpg",
      "./images/gallery/logos/5-Logo-Orhideo-www-marioiliev-com.jpg",
      "./images/gallery/logos/6-Logo-Nital-www-marioiliev-com.jpg",
      "./images/gallery/logos/8-Logo-Biss-www-marioiliev-com.jpg",
      "./images/gallery/logos/9-Logo-PeopleOfIdeas-www-marioiliev-com.jpg",
      "./images/gallery/logos/10-Logo-KREARO-www-marioiliev-com.jpg",
      "./images/gallery/logos/11-Logo-Lovely-gift-www-marioiliev-com.jpg",
    ],
    thumbs: [
      "./images/gallery/logos/1-Logo-HojaPlata-www-marioiliev-com-tmb.jpg",
      "./images/gallery/logos/2-Logo-osfeo-www-marioiliev-com-tmb.jpg",
      "./images/gallery/logos/3-Logo-Bourquin-www-marioiliev-com-tmb.jpg",
      "./images/gallery/logos/4-Logo-Shishmanovi-www-marioiliev-com-tmb.jpg",
      "./images/gallery/logos/5-Logo-Orhideo-www-marioiliev-com-tmb.jpg",
      "./images/gallery/logos/6-Logo-Nital-www-marioiliev-com-tmb.jpg",
      "./images/gallery/logos/8-Logo-Biss-www-marioiliev-com-tmb.jpg",
      "./images/gallery/logos/9-Logo-PeopleOfIdeas-www-marioiliev-com-tmb.jpg",
      "./images/gallery/logos/10-Logo-KREARO-www-marioiliev-com-tmb.jpg",
      "./images/gallery/logos/11-Logo-Lovely-gift-www-marioiliev-com-tmb.jpg",
    ],
  },
  // Business cards
  5: {
    images: [
      "./images/gallery/business-cards/1-business-card-www-marioiliev-com.jpg",
      "./images/gallery/business-cards/2-business-card-www-marioiliev-com.jpg",
      "./images/gallery/business-cards/3-business-card-www-marioiliev-com.jpg",
      "./images/gallery/business-cards/4-business-card-www-marioiliev-com.jpg",
      "./images/gallery/business-cards/5-business-card-www-marioiliev-com.jpg",
    ],
    thumbs: [
      "./images/gallery/business-cards/1-business-card-www-marioiliev-com-tmb.jpg",
      "./images/gallery/business-cards/2-business-card-www-marioiliev-com-tmb.jpg",
      "./images/gallery/business-cards/3-business-card-www-marioiliev-com-tmb.jpg",
      "./images/gallery/business-cards/4-business-card-www-marioiliev-com-tmb.jpg",
      "./images/gallery/business-cards/5-business-card-www-marioiliev-com-tmb.jpg",
    ],
  },
};

export default portfolioImagesMap;
